apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  config.yaml: |
{{ .Values.config | toYaml | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: plugins
data:
  plugins.yaml: |
{{ .Values.plugins | toYaml | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: job-config
data:
{{ .Values.jobConfig | toYaml | indent 2 }}
