apiVersion: apps/v1
kind: Deployment
metadata:
  name: deck
  labels:
    app: deck
spec:
  replicas: {{ .Values.replicas.deck }}
  selector:
    matchLabels:
      app: deck
  template:
    metadata:
      labels:
        app: deck
    spec:
      nodeSelector:
{{ toYaml .Values.nodeSelector.deck | indent 8 }}
      serviceAccountName: deck
      terminationGracePeriodSeconds: 30
      containers:
        - name: deck
          image: '{{ .Values.images.deck.repository }}:{{ .Values.images.deck.tag }}'
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          args:
            - --config-path=/etc/config/config.yaml
            - --job-config-path=/etc/job-config
            - --github-token-path=/etc/github/oauth
            - --plugin-config=/etc/plugins/plugins.yaml
            - --github-endpoint=https://api.github.com
            - --github-oauth-config-file=/etc/githuboauth/config
            - --oauth-url=/github-login
            - --tide-url=http://tide/
            - --hook-url=http://hook:8888/plugin-help
            - --cookie-secret=/etc/cookie/secret
            - --rerun-creates-job
            - --spyglass=true
            # - --build-cluster=/etc/cluster/cluster
            # - --redirect-http-to=prow.k8s.io
          volumeMounts:
            - name: config
              mountPath: /etc/config
              readOnly: true
            - name: oauth-token
              mountPath: /etc/github
              readOnly: true
            - name: plugins
              mountPath: /etc/plugins
              readOnly: true
            - name: cookie-secret
              mountPath: /etc/cookie
              readOnly: true
            - name: oauth-config
              mountPath: /etc/githuboauth
              readOnly: true
            - name: job-config
              mountPath: /etc/job-config
              readOnly: true
            # - name: cluster
            #   mountPath: /etc/cluster
            #   readOnly: true
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /healthz/ready
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 3
            timeoutSeconds: 600
      volumes:
        - name: config
          configMap:
            name: config
        - name: oauth-token
          secret:
            secretName: github-oauth-token
        - name: plugins
          configMap:
            name: plugins
        - name: cookie-secret
          secret:
            secretName: deck-cookie
        - name: oauth-config
          secret:
            secretName: github-oauth-config
        - name: job-config
          configMap:
            name: job-config
        # - name: cluster
        #   secret:
        #     defaultMode: 420
        #     secretName: build-cluster
