apiVersion: apps/v1
kind: Deployment
metadata:
  name: needs-rebase
  labels:
    app: needs-rebase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: needs-rebase
  template:
    metadata:
      labels:
        app: needs-rebase
    spec:
      nodeSelector:
{{ toYaml .Values.nodeSelector.needsRebase | indent 8 }}
      terminationGracePeriodSeconds: 180
      containers:
        - name: needs-rebase
          image: '{{ .Values.images.needsRebase.repository }}:{{ .Values.images.needsRebase.tag }}'
          imagePullPolicy: Always
          args:
            - --dry-run=false
            - --github-endpoint=https://api.github.com
          ports:
            - name: http
              containerPort: 8888
          volumeMounts:
            - name: hmac
              mountPath: /etc/webhook
              readOnly: true
            - name: oauth
              mountPath: /etc/github
              readOnly: true
            - name: plugins
              mountPath: /etc/plugins
              readOnly: true
      volumes:
        - name: hmac
          secret:
            secretName: github-hmac-token
        - name: oauth
          secret:
            secretName: github-oauth-token
        - name: plugins
          configMap:
            name: plugins
