apiVersion: apps/v1
kind: Deployment
metadata:
  name: plank
  labels:
    app: plank
spec:
  replicas: 1 # Do not scale up.
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: plank
  template:
    metadata:
      labels:
        app: plank
    spec:
      nodeSelector:
{{ toYaml .Values.nodeSelector.plank | indent 8 }}
      serviceAccountName: plank
      containers:
        - name: plank
          image: '{{ .Values.images.plank.repository }}:{{ .Values.images.plank.tag }}'
          args:
            - --dry-run=false
            - --config-path=/etc/config/config.yaml
            - --job-config-path=/etc/job-config
            - --github-endpoint=https://api.github.com
            - --skip-report=true
            # - --build-cluster=/etc/cluster/cluster
          volumeMounts:
            - name: oauth
              mountPath: /etc/github
              readOnly: true
            - name: config
              mountPath: /etc/config
              readOnly: true
            - name: job-config
              mountPath: /etc/job-config
              readOnly: true
            # - mountPath: /etc/cluster
            #   name: cluster
            #   readOnly: true
      volumes:
        - name: oauth
          secret:
            secretName: github-oauth-token
        - name: config
          configMap:
            name: config
        - name: job-config
          configMap:
            name: job-config
        # - name: cluster
        #   secret:
        #     defaultMode: 420
        #     secretName: build-cluster
