apiVersion: v1
kind: Secret
metadata:
  name: github-oauth-token
type: Opaque
stringData:
  oauth: {{ .Values.github.oauthToken }}
---
apiVersion: v1
kind: Secret
metadata:
  name: github-hmac-token
type: Opaque
stringData:
  hmac: {{ .Values.github.hmacToken }}
---
apiVersion: v1
kind: Secret
metadata:
  name: unsplash-api-key
type: Opaque
stringData:
  key: {{ .Values.unsplash.apiKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: deck-cookie
type: Opaque
stringData:
  secret: {{ .Values.deck.cookieSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: github-oauth-config
type: Opaque
stringData:
  config: |
{{ .Values.github.oauthConfig | toYaml | indent 4 }}
