apiVersion: v1
kind: Service
metadata:
  labels:
    app: tide
  name: tide
spec:
  selector:
    app: tide
  ports:
    - name: main
      port: 80
      targetPort: 8888
    - name: metrics
      port: 9090
  type: NodePort
