apiVersion: apps/v1
kind: Deployment
metadata:
  name: tide
  labels:
    app: tide
spec:
  replicas: 1 # Do not scale up.
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: tide
  template:
    metadata:
      labels:
        app: tide
    spec:
      nodeSelector:
{{ toYaml .Values.nodeSelector.tide | indent 8 }}
      serviceAccountName: tide
      containers:
        - name: tide
          image: '{{ .Values.images.tide.repository }}:{{ .Values.images.tide.tag }}'
          args:
            - --dry-run=false
            - --config-path=/etc/config/config.yaml
            - --job-config-path=/etc/job-config
            - --github-endpoint=https://api.github.com
            # - --gcs-credentials-file=/etc/service-account/service-account.json
            # - --history-uri=gs://k8s-prow/tide-history.json
            # - --status-path=gs://k8s-prow/tide-status-checkpoint.yaml
          ports:
            - name: http
              containerPort: 8888
          volumeMounts:
            - name: oauth
              mountPath: /etc/github
              readOnly: true
            - name: config
              mountPath: /etc/config
              readOnly: true
            - name: job-config
              mountPath: /etc/job-config
              readOnly: true
            # - name: service-account
            #   mountPath: /etc/service-account
            #   readOnly: true
      volumes:
        - name: oauth
          secret:
            secretName: github-oauth-token
        - name: config
          configMap:
            name: config
        - name: job-config
          configMap:
            name: job-config
        # - name: service-account
        #   secret:
        #     secretName: tide-history-service-account
