{{- if .Values.pipelineWebhook.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: webhook-controller
    app.kubernetes.io/name: tekton-pipelines
  name: tekton-pipelines-webhook
spec:
  replicas: {{ .Values.pipelineWebhook.replicas }}
  selector:
    matchLabels:
      app: tekton-pipelines-webhook
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: 'false'
      labels:
        app: tekton-pipelines-webhook
        app.kubernetes.io/component: webhook-controller
        app.kubernetes.io/name: tekton-pipelines
    spec:
      nodeSelector:
{{ toYaml .Values.pipelineWebhook.nodeSelector | indent 8 }}
      serviceAccountName: tekton-pipelines-controller
      containers:
        - name: webhook
          image: '{{ .Values.pipelineWebhook.image.repository }}:{{ .Values.pipelineWebhook.image.tag }}'
          env:
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - mountPath: /etc/config-logging
              name: config-logging
      volumes:
        - name: config-logging
          configMap:
            name: config-logging
{{- end }}
