name: tekton
apiVersion: v1
version: 0.8.0
appVersion: 0.8.0
home: https://github.com/eddycharly/helm-prow-tekton/helm/tekton
keywords:
  - helm
  - tekton pipeline
maintainers:
  - name: eddycharly
    email: charles.breteche@agriconomie.com
description: |
  ## Installation

  `helm upgrade --install my-tekton --namespace tekton ./tekton`

  This will install tekton pipelines and tekton dashboard in the tekton namespace.

  You can override default values, see the section **Chart Values** below.