name: tekton
apiVersion: v1
version: 0.8.0
appVersion: 0.8.0
home: https://github.com/eddycharly/helm-prow-tekton/helm/tekton
keywords:
  - helm
  - tekton pipeline
maintainers:
  - name: eddycharly
    email: charles.breteche@agriconomie.com
description: |
  This chart bootstraps installation of [tekton pipeline](https://github.com/tektoncd/pipeline).

  It optionnaly can install the following tekton additionnal components :
    - tekton pipeline webhook
    - tekton dashboard (see [here](https://github.com/tektoncd/dashboard))
    - tekton dashboard webhook extensions
