pipeline:

  image:
    # pipeline.image.repository -- Pipeline controller docker image repository
    repository: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller@sha256
    # pipeline.image.tag -- Pipeline controller docker image tag
    tag: 72a2bda21b5bc23550e94fdf7cee8a6e5bd82601f5d81a6237fc2b8c42321a59

  # pipeline.replicas -- Pipeline controller replicas
  replicas: 1

  # pipeline.nodeSelector -- Pipeline controller node selector
  nodeSelector: {}

  helperImages:

    bash-noop-image:
      # pipeline.helperImages.bash-noop-image.repository -- Pipeline controller bash-noop-image helper image repository
      repository: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/bash@sha256
      # pipeline.helperImages.bash-noop-image.tag -- Pipeline controller bash-noop-image helper image tag
      tag: a96b5840cdeb2a6598a8566a8607b925732286a8fdf15147be3591b7c7fb41f7

    build-gcs-fetcher-image:
      # pipeline.helperImages.build-gcs-fetcher-image.repository -- Pipeline controller build-gcs-fetcher-image helper image repository
      repository: gcr.io/tekton-releases/github.com/tektoncd/pipeline/vendor/github.com/googlecloudplatform/cloud-builders/gcs-fetcher/cmd/gcs-fetcher@sha256
      # pipeline.helperImages.build-gcs-fetcher-image.tag -- Pipeline controller build-gcs-fetcher-image helper image tag
      tag: 5be2e14ed6b986198beca21a93af34e807586dcf9155babeca7f5971a2fa0311

    creds-image:
      # pipeline.helperImages.creds-image.repository -- Pipeline controller creds-image helper image repository
      repository: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/creds-init@sha256
      # pipeline.helperImages.creds-image.tag -- Pipeline controller creds-image helper image tag
      tag: 8f8c43a115984e90db3b0cb3fcd46e1699ec15515ca7d258571a44c7d76040ca

    entrypoint-image:
      # pipeline.helperImages.entrypoint-image.repository -- Pipeline controller entrypoint-image helper image repository
      repository: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint@sha256
      # pipeline.helperImages.entrypoint-image.tag -- Pipeline controller entrypoint-image helper image tag
      tag: 5c2a7261d923b8af29ad3be34a9c9a3abd1ed11a030ca1cc207293d203755ab4

    git-image:
      # pipeline.helperImages.git-image.repository -- Pipeline controller git-image helper image repository
      repository: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init@sha256
      # pipeline.helperImages.git-image.tag -- Pipeline controller git-image helper image tag
      tag: 00466e8ec7d8a289140893523d33261ba5006dfb1bd9b96aee2736fc739dba5a

    gsutil-image:
      # pipeline.helperImages.gsutil-image.repository -- Pipeline controller gsutil-image helper image repository
      repository: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/gsutil@sha256
      # pipeline.helperImages.gsutil-image.tag -- Pipeline controller gsutil-image helper image tag
      tag: 0130ec562b897c5929123d4e14cd3271cd58102f1f411f52cb6f415088bf5944
    imagedigest-exporter-image:
      # pipeline.helperImages.imagedigest-exporter-image.repository -- Pipeline controller imagedigest-exporter-image helper image repository
      repository: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/imagedigestexporter@sha256
      # pipeline.helperImages.imagedigest-exporter-image.tag -- Pipeline controller imagedigest-exporter-image helper image tag
      tag: 23e2de68c86de494aba98dabf02b175efc051827c52350bdd9a89f6a3d969ea9

    kubeconfig-writer-image:
      # pipeline.helperImages.kubeconfig-writer-image.repository -- Pipeline controller kubeconfig-writer-image helper image repository
      repository: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/kubeconfigwriter@sha256
      # pipeline.helperImages.kubeconfig-writer-image.tag -- Pipeline controller kubeconfig-writer-image helper image tag
      tag: 912d30334e63899f3875806b0633b5ddf3470d64fbd2333fc2c534afcfa9872d

    nop-image:
      # pipeline.helperImages.nop-image.repository -- Pipeline controller nop-image helper image repository
      repository: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/nop@sha256
      # pipeline.helperImages.nop-image.tag -- Pipeline controller nop-image helper image tag
      tag: b77955ba2711e1ba30ab48670bcafd725ddc01a105d173256e158053914dc42c
      
    pr-image:
      # pipeline.helperImages.pr-image.repository -- Pipeline controller pr-image helper image repository
      repository: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/pullrequest-init@sha256
      # pipeline.helperImages.pr-image.tag -- Pipeline controller pr-image helper image tag
      tag: 26a181a89c00ab840599508e905d1cfeed5db2b4ea41fbcc63c22979389e4a46

  config:
    # pipeline.config.artifactBucket -- Pipeline configuration for artifact bucket (see https://github.com/tektoncd/pipeline/blob/master/docs/install.md)
    artifactBucket: {}

    # pipeline.config.artifactPvc -- Pipeline configuration for artifact pvc (see https://github.com/tektoncd/pipeline/blob/master/docs/install.md)
    artifactPvc: {}

    # pipeline.config.defaults -- Pipeline configuration for default values (see https://github.com/tektoncd/pipeline/blob/master/docs/install.md)
    defaults: {}

    # pipeline.config.logging -- Pipeline configuration for logging (see https://github.com/tektoncd/pipeline/blob/master/docs/install.md)
    logging:
      loglevel.controller: info
      loglevel.webhook: info
      zap-logger-config: |
        {
          "level": "info",
          "development": false,
          "sampling": {
            "initial": 100,
            "thereafter": 100
          },
          "outputPaths": ["stdout"],
          "errorOutputPaths": ["stderr"],
          "encoding": "json",
          "encoderConfig": {
            "timeKey": "",
            "levelKey": "level",
            "nameKey": "logger",
            "callerKey": "caller",
            "messageKey": "msg",
            "stacktraceKey": "stacktrace",
            "lineEnding": "",
            "levelEncoder": "",
            "timeEncoder": "",
            "durationEncoder": "",
            "callerEncoder": ""
          }
        }

    # pipeline.config.observability -- Pipeline configuration for observability (see https://github.com/tektoncd/pipeline/blob/master/docs/install.md)
    observability: {}

pipelineWebhook:

  # pipelineWebhook.enabled -- Enable pipeline webhook
  enabled: true

  image:
    # pipelineWebhook.image.repository -- Pipeline webhook docker image repository
    repository: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook@sha256
    # pipelineWebhook.image.tag -- Pipeline webhook docker image tag
    tag: 1d6336f2748cb8e5c19b17191a54c6adbbc77e2d1c60818f93282ec482bb2957

  # pipelineWebhook.replicas -- Pipeline webhook replicas
  replicas: 1

  # pipelineWebhook.nodeSelector -- Pipeline webhook node selector
  nodeSelector: {}

dashboard:

  # dashboard.enabled -- Enable dashboard
  enabled: true

  image:
    # dashboard.image.repository -- Dashboard docker image repository
    repository: gcr.io/tekton-releases/github.com/tektoncd/dashboard/cmd/dashboard@sha256
    # dashboard.image.tag -- Dashboard docker image tag
    tag: b985769636204f2d736e20dbafa27ff68ba07c218445925da094a2dd8ab07a6a

  # dashboard.replicas -- Dashboard replicas
  replicas: 1

  # dashboard.nodeSelector -- Dashboard node selector
  nodeSelector: {}

  ingress:
    # dashboard.ingress.enabled -- Enable dashboard ingress
    enabled: false
    # dashboard.ingress.annotations -- Dashboard ingress annotations
    annotations: {}
    # dashboard.ingress.host -- Dashboard ingress host name
    host: example.com

dashboardWebhook:

  # dashboardWebhook.enabled -- Enable dashboard webhook
  enabled: true

  image:
    # dashboardWebhook.image.repository -- Dashboard webhook docker image repository
    repository: gcr.io/tekton-releases/github.com/tektoncd/experimental/webhooks-extension/cmd/extension@sha256
    # dashboardWebhook.image.tag -- Dashboard webhook docker image tag
    tag: db812c6ef08e84870b3ed294b00ac5bdabbc67efca177786d6f307150674f2a2

  # dashboardWebhook.replicas -- Dashboard webhook replicas
  replicas: 1

  # dashboardWebhook.nodeSelector -- Dashboard webhook node selector
  nodeSelector: {}
